"""Dealer-independent domain types for the dealership webchat."""

from .common import (
    Address,
    BookingStatus,
    CustomerIdentity,
    Department,
    Money,
    Page,
    ReceivedStatus,
)
from .dealerships import (
    BusinessInformation,
    ContactMethod,
    DealerLocation,
    DealershipMessage,
    DealershipMessageRequest,
    HolidayOpening,
    OpeningHours,
    OpeningPeriod,
)
from .dealer import DealerAdapter
from .errors import DealerError, DealerErrorKind, DealerFailure, FieldViolation
from .sales import (
    Callback,
    CallbackRequest,
    CallbackStatus,
    EnquiryType,
    InterestStatus,
    PartExchangeCondition,
    PartExchangeRequest,
    PartExchangeStatus,
    PartExchangeValuation,
    PartExchangeVehicle,
    SalesEnquiry,
    SalesEnquiryRequest,
    TestDriveBooking,
    TestDriveBookingRequest,
    TestDriveSlot,
    TestDriveSlotSearch,
    VehicleInterest,
    VehicleInterestRequest,
)

from .vehicles import (
    AvailabilitySlot,
    OfferSearch,
    Vehicle,
    VehicleAvailability,
    VehicleAvailabilityStatus,
    VehicleDetails,
    VehicleOffer,
    VehicleSearch,
    VehicleSort,
)
from .workshop import (
    WorkshopBooking,
    WorkshopBookingAmendment,
    WorkshopBookingDetails,
    WorkshopBookingLookup,
    WorkshopBookingRequest,
    WorkshopCancellationRequest,
    WorkshopService,
    WorkshopSlot,
    WorkshopSlotSearch,
)

__all__ = [
    "Address",
    "AvailabilitySlot",
    "BookingStatus",
    "BusinessInformation",
    "Callback",
    "CallbackRequest",
    "CallbackStatus",
    "CustomerIdentity",
    "ContactMethod",
    "DealerLocation",
    "DealerAdapter",
    "DealerError",
    "DealerErrorKind",
    "DealerFailure",
    "DealershipMessage",
    "DealershipMessageRequest",
    "Department",
    "EnquiryType",
    "FieldViolation",
    "InterestStatus",
    "HolidayOpening",
    "Money",
    "OfferSearch",
    "OpeningHours",
    "OpeningPeriod",
    "Page",
    "PartExchangeCondition",
    "PartExchangeRequest",
    "PartExchangeStatus",
    "PartExchangeValuation",
    "PartExchangeVehicle",
    "ReceivedStatus",
    "SalesEnquiry",
    "SalesEnquiryRequest",
    "TestDriveBooking",
    "TestDriveBookingRequest",
    "TestDriveSlot",
    "TestDriveSlotSearch",
    "Vehicle",
    "VehicleAvailability",
    "VehicleAvailabilityStatus",
    "VehicleDetails",
    "VehicleOffer",
    "VehicleSearch",
    "VehicleSort",
    "VehicleInterest",
    "VehicleInterestRequest",
    "WorkshopBooking",
    "WorkshopBookingAmendment",
    "WorkshopBookingDetails",
    "WorkshopBookingLookup",
    "WorkshopBookingRequest",
    "WorkshopCancellationRequest",
    "WorkshopService",
    "WorkshopSlot",
    "WorkshopSlotSearch",
]
